### ISSUE TITLE
Windows 11中，Microsoft Word暫時未能正常使用字體名稱超過31字元的字體，可否縮短英文字體名稱以作權宜之計

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/Shanggu#79]
![Screenshot 2024-03-08 234504](https://github.com/GuiWonder/SourceHanToClassic/assets/51369959/3b9896fc-a4df-4182-b7e9-7c9bd3fdbc5d)
例如"Advocate Ancient Sans _region_ W&zwnj;_n_"

**Comment by GuiWonder** [comment]
按照最長的「Advocate Ancient Rounded HW JP ExtraLight」來計算，除去「 Rounded HW JP ExtraLight」只剩下 6 個字元空間來命名，因此可能需要較大的更改。

**Comment by GuiWonder** [comment]
> “Advocate Ancient Rounded (_region_) (EL/L/M/N/B/H)”可行嗎？只用了30個字元。

 不過 "Advocate Ancient Rounded HW JP EL" 的長度是 33 仍然過長，目前正在考慮換掉 "Advocate Ancient"，比如使用漢語拼音 "Shanggu"。

**Comment by GuiWonder** [comment]
@elvis-hrvat Thank you very much! I'm sorry it's been renamed. Since this issue caused serious problems, I didn't spend more time taking names. Hanyu Pinyin has been used for the time being. By the way, the name "dzyangku" is slightly longer, the new name needs to be within seven letters.

---
Below are the pronunciations (in Romanized characters) of "尚古" in some regions. Maybe they can be referenced.
以下是「尚古」在部分地區的讀音（羅馬字），或可參考。

shouko shanggu sanggo soenggu siongkoo

**Comment by GuiWonder** [comment]
> 我個人覺得「Shanggu」就挺好，簡單又好記，以前的名稱實在太難拼了。我並不贊成使用古漢語的讀音進行拉丁化，古漢語的讀音有幾個人能懂？這種音標式的名稱看上去像亂碼一樣，一點都不像英文單詞，而且拼讀起來奇奇怪怪的，給人以錯誤地聯想。另外「ku」音聽上去太難聽，不建議使用。上面提到的名稱中，我比較喜歡「shouko」看上去更像一個單詞。都用上「英文名稱」了還在乎那些博大的古漢語文化沒什麼意義，中文名用對就行了，英文名只要別太過分就行了。

有道理。我在上面提到的五種羅馬字轉換是中日韓粵閩的羅馬字，可以看出雖然使用的方案不同，但是都很相似；放在英文中拼讀（可藉助工具）發音也都相似。相比外國人名的中文譯名大部分都是近似音，這五種方案都沒有問題。反觀「dzyangH kuX」這套方案在英文中甚至都不能拼讀，更不用說用來表音。至於「ku」音在現代漢語中容易被聯想到「哭」、「苦」。在日語中也一樣，比如在日本數字 9 有時是需要避諱的，因爲數字 9 的讀音是「ku(苦)」。所以很多人都不喜歡「ku」音。
